### ISSUE TITLE
xlocale.h on Ubuntu 18.04

### ISSUE THREAD

**Issue by snoyberg** [ppelleti/hs-mercury-api#2]
Trying to compile this on Ubuntu 18.04, I get the following build error:

```
[6 of 6] Compiling System.Hardware.MercuryApi.Testing ( dist/build/System/Hardware/MercuryApi/Testing.hs, dist/build/System/Hardware/MercuryApi/Testing.o )

cbits/glue/glue.c:9:10: error:
     fatal error: xlocale.h: No such file or directory
     #include <xlocale.h>
              ^~~~~~~~~~~
  |
9 | #include <xlocale.h>
  |          ^
compilation terminated.
`gcc' failed in phase `C Compiler'. (Exit code: 1)
```

It looks like this should be resolved in the most recent version here on Github, since `xlocale.h` should only be used on `__APPLE__` (see: https://github.com/ppelleti/hs-mercury-api/commit/440482a8d1b687cc3448153d944cbf4bd4cd3ca7). Would it be possible to get a release? Until then, I'm going to have to drop this from Stackage Nightly.

**Comment by mignon-p** [comment]
OK, I have uploaded [mercury-api-0.1.0.2](https://hackage.haskell.org/package/mercury-api-0.1.0.2).

**Comment by snoyberg** [comment]
Thanks!
